In [4]:
from scipy.optimize import linprog
c = [-6,0, -20]
A = [[0, 1, 4], [3, -1, 2]]
b = [10, 11]
x0_bounds = (0, None)
x1_bounds = (0, None)
x2_bounds = (0, None)
res = linprog(c, A_ub=A, b_ub=b, bounds=(x0_bounds, x1_bounds, x2_bounds), options={"disp": True})

Optimization terminated successfully.
         Current function value: -62.000000  
         Iterations: 2


In [5]:
res.x

array([2. , 0. , 2.5])

In [12]:
import numpy as np
from numpy.linalg import inv
Binv = [[1/3, 0, -2/3],[0, 1, 1], [1/3, 0, 1/3]]
Binvb = [[1/3], [6], [13/3]]
BinvA = [[1, -1/3,0, 1/3,0, -2/3],[0,2, 0,0, 1,1], [0,2/3, 1,1/3,0, 1/3]]
A = np.matmul(inv(Binv), BinvA)  

In [10]:
A

array([[ 1.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00, -1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  5.55111512e-17],
       [-1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [14]:
np.matmul(inv(Binv), [[0],[4],[0]])

array([[0.],
       [4.],
       [0.]])

In [15]:
inv(Binv)

array([[ 1.,  0.,  2.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])