In [11]:
from scipy.optimize import linprog
c = [-2,-1,1]
A_eq = [[0,1,2]]
b_eq = [3]
A_ub= [[1, 2,1], [-1,1,-2]]
b_ub= [8,4]
x1_bounds = (None, None)
x2_bounds = (0, None)
x3_bounds = (0, None)

res = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=(x1_bounds, x2_bounds,x3_bounds),options={"disp": True})

Optimization terminated successfully.
         Current function value: -11.500000  
         Iterations: 2


In [12]:
res.x

array([6.5, 0. , 1.5])

In [30]:
from scipy.optimize import linprog
c = [-2,-1,1]
A = [[1, 2,1], [-1,1,-2]]
b = [16,4]
x0_bounds = (0, None)
x1_bounds = (0, None)
x2_bounds = (0, None)
res = linprog(c, A_ub=A, b_ub=b, bounds=(x0_bounds, x1_bounds,x2_bounds), options={"disp": True})

Optimization terminated successfully.
         Current function value: -32.000000  
         Iterations: 1


In [31]:
res.x

array([16.,  0.,  0.])

In [11]:
import numpy as np
from numpy.linalg import inv
Binv = [[1/3, 0, -2/3],[0, 1, 1], [1/3, 0, 1/3]]
Binvb = [[1/3], [6], [13/3]]
BinvA = [[1, -1/3,0, 1/3,0, -2/3],[0,2, 0,0, 1,1], [0,2/3, 1,1/3,0, 1/3]]
A = np.matmul(inv(Binv), BinvA)  

In [14]:
A = [[1,1,2,1,0,0,], [1,1,-1,0,1,0], [-1,1,1,0,0,1]]
B = [[2,0,0],[-1,1,0],[1,0,1]]
CBT = [-4,0,0]
np.matmul(CBT, np.matmul(inv(B), A))

array([-2., -2., -4., -2.,  0.,  0.])

In [29]:
A = [[1,1,2,1,0,0,], [1,1,-1,0,1,0], [-1,1,1,0,0,1]]
Binv = [[1/3, 0, -2/3],[0, 1, 1], [1/3, 0, 1/3]]
Binvb = [[1/3], [6], [13/3]]
b = np.matmul(inv(Binv), Binvb)
CBT = [1,0,-4]
Cbar = [1,1,-4,0,0,0]-np.matmul([1,0,-4], np.matmul(Binv, A))

In [30]:
b

array([[9.],
       [2.],
       [4.]])

In [33]:
[1,1,-4,0,0,0]-np.matmul([1,0,-4], BinvA)

array([0., 4., 0., 1., 0., 2.])

array([[9.],
       [2.],
       [4.]])

array([0., 4., 0., 1., 0., 2.])

In [35]:
import numpy as np
from numpy.linalg import inv
Binv = [[1/4, 0],[-1/6, 1/3]]
BinvA = [[0, 1/4, 1, 1/4, 0],[1,-1/2,0,-1/6, 1/3]]
Binvb = [5/2, 2]
A = np.matmul(inv(Binv), BinvA)
b= np.matmul(inv(Binv), Binvb)

In [82]:
np.matmul(Binv, [-1,0,0])

array([-0.5,  1. , -5. ])

In [37]:
b

array([10., 11.])

In [96]:
import numpy as np
from numpy.linalg import inv
Binv = [[1/2, 1/5, -1],[-1, 0, 1/2], [5, -3/10, 2]]
Binvb = [3,1,7]
BinvA = [[1,0,0,-1,0,1/2,1/5,-1],[0,1,0,2,1,-1,0,1/2], [0,0,1,-1,-2,5,-3/10,2]]

In [99]:
np.matmul([2,1/10,2], inv(Binv))

array([2., 4., 1.])

In [100]:
b = np.matmul(inv(Binv), Binvb)
b

array([ 1.55555556, 36.66666667,  5.11111111])

0.5555555555555556

In [74]:
c_1 = np.matmul([2,1/10, 2],inv(Binv))
c_2 = [-2,0] + np.matmul(c_1, [[-1,0],[2,1],[-1,-2]])
c = np.concatenate((c_1,c_2))

In [75]:
c

array([2., 4., 1., 3., 2.])

In [76]:
A.shape

(3, 5)

In [77]:
from scipy.optimize import linprog

A = A[:,0:5]
b = np.matmul(inv(Binv), Binvb)
c = -c
x0_bounds = (0, None)
x1_bounds = (0, None)
x2_bounds = (0, None)
x3_bounds = (0, None)
x4_bounds = (0, None)
res = linprog(c, A_ub=A, b_ub=b, bounds=(x0_bounds, x1_bounds,x2_bounds, x3_bounds, x4_bounds), options={"disp": True})

Optimization terminated successfully.
         Current function value: -17.000000  
         Iterations: 3


In [110]:
import numpy as np
from numpy.linalg import inv
Binv = [[5/2,0,1], [-10,1,-10],[-1,0,1/2]]
b = [14/9, 110/3, 46/9]
np.matmul(Binv, [-1,0,0])

array([-2.5, 10. ,  1. ])

In [111]:
np.matmul(Binv, b)

array([  9., -30.,   1.])

In [1]:
from scipy.optimize import linprog
c = [-2,1,-1]
A = [[0, 1,1], [-1,2,0]]
b = [6,4]
x0_bounds = (0, None)
x1_bounds = (0, None)
x2_bounds = (0, None)
res = linprog(c, A_ub=A, b_ub=b, bounds=(x0_bounds, x1_bounds,x2_bounds), options={"disp": True})

Optimization failed. The problem appears to be unbounded.
         Iterations: 0


In [ ]:
n